package net.minecraft.AgeOfMinecraft;

import net.minecraft.AgeOfMinecraft.entity.tame.cameos.EntityBoneAttack;
import net.minecraft.AgeOfMinecraft.entity.tame.cameos.EntityGasterBlaster;
import net.minecraft.AgeOfMinecraft.entity.tame.cameos.EntitySans;
import net.minecraft.AgeOfMinecraft.entity.tame.other.EntityManaOrb;
import net.minecraft.AgeOfMinecraft.entity.tame.other.EntityPortal;
import net.minecraft.AgeOfMinecraft.entity.tame.other.EntityPortalLightning;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityBat;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityChicken;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityCow;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityMooshroom;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityOcelot;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityParrot;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityPig;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityRabbit;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntitySheep;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityEndermite;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityLlama;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntitySilverfish;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntitySnowman;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntitySquid;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityVillager;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityWolf;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityCreeper;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityMagmaCube;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityPolarBear;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityPrisonSlime;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntitySkeleton;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntitySlime;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntitySpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityTippedArrowOther;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityVex;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityZombie;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityBlaze;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityCaveSpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityCreeder;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityEnderman;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityGhast;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityGuardian;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityIceSpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityIcyEnderCreeper;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityPigZombie;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityPrisonSpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityShulker;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityVindicator;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityWitch;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityAbomniableSnowman;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityDisintigrationRay;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityElderGuardian;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityEnderDragon;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityEversource;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityEvoker;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityFrostRay;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityGhasther;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityGiant;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityIceGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityIllusioner;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityInvisibleFangsProjectile;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityIronGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityMagicMissile;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityMagmaGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityPrisonGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntitySnowballHarmful;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityWither;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.dragonphases.EntityAreaEffectCloudOther;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityCommandBlockWither;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStorm;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormHead;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormSkull;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormTentacle;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormTentacleDevourer;
import net.minecraft.AgeOfMinecraft.entity.untame.tier5.EntityDarkness;
import net.minecraft.AgeOfMinecraft.events.EngenderGeneralEvent;
import net.minecraft.AgeOfMinecraft.events.EngenderMusicEvent;
import net.minecraft.AgeOfMinecraft.registry.EBlock;
import net.minecraft.AgeOfMinecraft.registry.EItem;
import net.minecraft.AgeOfMinecraft.renders.RenderAbomniableSnowman;
import net.minecraft.AgeOfMinecraft.renders.RenderBat;
import net.minecraft.AgeOfMinecraft.renders.RenderBlaze;
import net.minecraft.AgeOfMinecraft.renders.RenderBoneAttack;
import net.minecraft.AgeOfMinecraft.renders.RenderCaveSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderChicken;
import net.minecraft.AgeOfMinecraft.renders.RenderCommandBlockWither;
import net.minecraft.AgeOfMinecraft.renders.RenderCow;
import net.minecraft.AgeOfMinecraft.renders.RenderCreeder;
import net.minecraft.AgeOfMinecraft.renders.RenderCreeper;
import net.minecraft.AgeOfMinecraft.renders.RenderEnderDragon;
import net.minecraft.AgeOfMinecraft.renders.RenderEnderman;
import net.minecraft.AgeOfMinecraft.renders.RenderEndermite;
import net.minecraft.AgeOfMinecraft.renders.RenderEversource;
import net.minecraft.AgeOfMinecraft.renders.RenderEvoker;
import net.minecraft.AgeOfMinecraft.renders.RenderGasterBlaster;
import net.minecraft.AgeOfMinecraft.renders.RenderGhast;
import net.minecraft.AgeOfMinecraft.renders.RenderGhasther;
import net.minecraft.AgeOfMinecraft.renders.RenderGiant;
import net.minecraft.AgeOfMinecraft.renders.RenderGuardian;
import net.minecraft.AgeOfMinecraft.renders.RenderIceGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderIceSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderIcyEnderCreeper;
import net.minecraft.AgeOfMinecraft.renders.RenderIllusioner;
import net.minecraft.AgeOfMinecraft.renders.RenderIronGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderLlama;
import net.minecraft.AgeOfMinecraft.renders.RenderMagicMissile;
import net.minecraft.AgeOfMinecraft.renders.RenderMagmaCube;
import net.minecraft.AgeOfMinecraft.renders.RenderMagmaGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderManaOrb;
import net.minecraft.AgeOfMinecraft.renders.RenderMooshroom;
import net.minecraft.AgeOfMinecraft.renders.RenderNullEntity;
import net.minecraft.AgeOfMinecraft.renders.RenderOcelot;
import net.minecraft.AgeOfMinecraft.renders.RenderParrot;
import net.minecraft.AgeOfMinecraft.renders.RenderPig;
import net.minecraft.AgeOfMinecraft.renders.RenderPigZombie;
import net.minecraft.AgeOfMinecraft.renders.RenderPolarBear;
import net.minecraft.AgeOfMinecraft.renders.RenderPortal;
import net.minecraft.AgeOfMinecraft.renders.RenderPrisonGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderPrisonSlime;
import net.minecraft.AgeOfMinecraft.renders.RenderPrisonSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderRabbit;
import net.minecraft.AgeOfMinecraft.renders.RenderSans;
import net.minecraft.AgeOfMinecraft.renders.RenderSheep;
import net.minecraft.AgeOfMinecraft.renders.RenderShulker;
import net.minecraft.AgeOfMinecraft.renders.RenderSilverfish;
import net.minecraft.AgeOfMinecraft.renders.RenderSkeleton;
import net.minecraft.AgeOfMinecraft.renders.RenderSlime;
import net.minecraft.AgeOfMinecraft.renders.RenderSnowMan;
import net.minecraft.AgeOfMinecraft.renders.RenderSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderSquid;
import net.minecraft.AgeOfMinecraft.renders.RenderStormSkull;
import net.minecraft.AgeOfMinecraft.renders.RenderVex;
import net.minecraft.AgeOfMinecraft.renders.RenderVillager;
import net.minecraft.AgeOfMinecraft.renders.RenderVindicator;
import net.minecraft.AgeOfMinecraft.renders.RenderWitch;
import net.minecraft.AgeOfMinecraft.renders.RenderWither;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStorm;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStormHead;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStormTentacle;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStormTentacleDevourer;
import net.minecraft.AgeOfMinecraft.renders.RenderWolf;
import net.minecraft.AgeOfMinecraft.renders.RenderZombie;
import net.minecraft.AgeOfMinecraft.renders.darkness.RenderDarkness;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.client.renderer.entity.RenderSnowball;
import net.minecraft.client.renderer.entity.RenderTippedArrow;
import net.minecraft.init.Items;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class ClientProxy extends CommonProxy {
  public void preInit(FMLPreInitializationEvent e) {
    renderEntities();
    EngenderGeneralEvent.musicTicker = new EngenderMusicEvent(Minecraft.func_71410_x());
    super.preInit(e);
  }
  
  public void init(FMLInitializationEvent e) {
    super.init(e);
  }
  
  public void postInit(FMLPostInitializationEvent e) {
    super.postInit(e);
    EItem.registerRenders();
    EBlock.registerRenders();
    if (Loader.isModLoaded("abyssalcraft"))
      EItem.registerAbyRenders(); 
    if (Loader.isModLoaded("draconicevolution"))
      EItem.registerDracRenders(); 
    if (Loader.isModLoaded("mutantbeasts"))
      EItem.registerMutantRenders(); 
  }
  
  public void renderEntities() {
    RenderingRegistry.registerEntityRenderingHandler(EntityManaOrb.class, manager -> new RenderManaOrb(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityAreaEffectCloudOther.class, manager -> new RenderNullEntity(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityEversource.class, manager -> new RenderEversource(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityIceSpider.class, manager -> new RenderIceSpider(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityCreeder.class, manager -> new RenderCreeder(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityIcyEnderCreeper.class, manager -> new RenderIcyEnderCreeper(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityIceGolem.class, manager -> new RenderIceGolem(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityMagmaGolem.class, manager -> new RenderMagmaGolem(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPrisonSlime.class, manager -> new RenderPrisonSlime(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPrisonSpider.class, manager -> new RenderPrisonSpider(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPrisonGolem.class, manager -> new RenderPrisonGolem(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityGhasther.class, manager -> new RenderGhasther(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityAbomniableSnowman.class, manager -> new RenderAbomniableSnowman(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityMagicMissile.class, manager -> new RenderMagicMissile(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityEvoker.class, manager -> new RenderEvoker(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityLlama.class, manager -> new RenderLlama(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityIllusioner.class, manager -> new RenderIllusioner(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityVindicator.class, manager -> new RenderVindicator(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityVex.class, manager -> new RenderVex(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPolarBear.class, manager -> new RenderPolarBear(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityCaveSpider.class, manager -> new RenderCaveSpider(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySpider.class, manager -> new RenderSpider(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPig.class, manager -> new RenderPig(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySheep.class, manager -> new RenderSheep(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityCow.class, manager -> new RenderCow(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityMooshroom.class, manager -> new RenderMooshroom(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWolf.class, manager -> new RenderWolf(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityChicken.class, manager -> new RenderChicken(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityParrot.class, manager -> new RenderParrot(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityOcelot.class, manager -> new RenderOcelot(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityRabbit.class, manager -> new RenderRabbit(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySilverfish.class, manager -> new RenderSilverfish(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityEndermite.class, manager -> new RenderEndermite(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityCreeper.class, manager -> new RenderCreeper(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityEnderman.class, manager -> new RenderEnderman(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySnowman.class, manager -> new RenderSnowMan(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySkeleton.class, manager -> new RenderSkeleton(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWitch.class, manager -> new RenderWitch(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityBlaze.class, manager -> new RenderBlaze(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPigZombie.class, manager -> new RenderPigZombie(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityZombie.class, manager -> new RenderZombie(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySlime.class, manager -> new RenderSlime(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityMagmaCube.class, manager -> new RenderMagmaCube(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityGiant.class, manager -> new RenderGiant(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityGhast.class, manager -> new RenderGhast(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySquid.class, manager -> new RenderSquid(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityVillager.class, manager -> new RenderVillager(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityIronGolem.class, manager -> new RenderIronGolem(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityBat.class, manager -> new RenderBat(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityGuardian.class, manager -> new RenderGuardian(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityElderGuardian.class, manager -> new RenderGuardian(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityShulker.class, manager -> new RenderShulker(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityEnderDragon.class, manager -> new RenderEnderDragon(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWither.class, manager -> new RenderWither(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityCommandBlockWither.class, manager -> new RenderCommandBlockWither(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormSkull.class, manager -> new RenderStormSkull(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStorm.class, manager -> new RenderWitherStorm(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityDarkness.class, manager -> new RenderDarkness(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormHead.class, manager -> new RenderWitherStormHead(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormTentacle.class, manager -> new RenderWitherStormTentacle(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormTentacleDevourer.class, manager -> new RenderWitherStormTentacleDevourer(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPortal.class, manager -> new RenderPortal(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityPortalLightning.class, manager -> new RenderNullEntity(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityDisintigrationRay.class, manager -> new RenderNullEntity(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityInvisibleFangsProjectile.class, manager -> new RenderNullEntity(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityFrostRay.class, manager -> new RenderNullEntity(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySnowballHarmful.class, manager -> new RenderSnowball(manager, Items.field_151126_ay, Minecraft.func_71410_x().func_175599_af()));
    RenderingRegistry.registerEntityRenderingHandler(EntityTippedArrowOther.class, manager -> new RenderTippedArrow(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntitySans.class, manager -> new RenderSans(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityBoneAttack.class, manager -> new RenderBoneAttack(manager));
    RenderingRegistry.registerEntityRenderingHandler(EntityGasterBlaster.class, manager -> new RenderGasterBlaster(manager));
  }
}
