package net.minecraft.AgeOfMinecraft;

import net.minecraft.AgeOfMinecraft.entity.tame.cameos.EntityBoneAttack;
import net.minecraft.AgeOfMinecraft.entity.tame.cameos.EntityGasterBlaster;
import net.minecraft.AgeOfMinecraft.entity.tame.cameos.EntitySans;
import net.minecraft.AgeOfMinecraft.entity.tame.other.EntityManaOrb;
import net.minecraft.AgeOfMinecraft.entity.tame.other.EntityPortal;
import net.minecraft.AgeOfMinecraft.entity.tame.other.EntityPortalLightning;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityBat;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityChicken;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityCow;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityMooshroom;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityOcelot;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityParrot;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityPig;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntityRabbit;
import net.minecraft.AgeOfMinecraft.entity.tame.tier1.EntitySheep;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityEndermite;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityLlama;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntitySilverfish;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntitySnowman;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntitySquid;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityVillager;
import net.minecraft.AgeOfMinecraft.entity.tame.tier2.EntityWolf;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityCreeper;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityMagmaCube;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityPolarBear;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityPrisonSlime;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntitySkeleton;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntitySlime;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntitySpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityTippedArrowOther;
import net.minecraft.AgeOfMinecraft.entity.tame.tier3.EntityVex;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityBlaze;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityCaveSpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityCreeder;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityEnderman;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityGhast;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityGuardian;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityIceSpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityIcyEnderCreeper;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityPigZombie;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityPrisonSpider;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityShulker;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityVindicator;
import net.minecraft.AgeOfMinecraft.entity.tame.tier4.EntityWitch;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityAbomniableSnowman;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityDisintigrationRay;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityElderGuardian;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityEnderDragon;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityEversource;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityEvoker;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityFrostRay;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityGhasther;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityGiant;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityIceGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityIllusioner;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityInvisibleFangsProjectile;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityIronGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityMagicMissile;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityMagmaGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityPrisonGolem;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntitySnowballHarmful;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.EntityWither;
import net.minecraft.AgeOfMinecraft.entity.tame.tier5.dragonphases.EntityAreaEffectCloudOther;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityCommandBlockWither;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStorm;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormHead;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormSkull;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormTentacle;
import net.minecraft.AgeOfMinecraft.entity.tame.tier6.EntityWitherStormTentacleDevourer;
import net.minecraft.AgeOfMinecraft.events.EngenderGeneralEvent;
import net.minecraft.AgeOfMinecraft.events.EngenderMusicEvent;
import net.minecraft.AgeOfMinecraft.registry.EItem;
import net.minecraft.AgeOfMinecraft.renders.RenderAbomniableSnowman;
import net.minecraft.AgeOfMinecraft.renders.RenderBat;
import net.minecraft.AgeOfMinecraft.renders.RenderBlaze;
import net.minecraft.AgeOfMinecraft.renders.RenderBoneAttack;
import net.minecraft.AgeOfMinecraft.renders.RenderCaveSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderChicken;
import net.minecraft.AgeOfMinecraft.renders.RenderCommandBlockWither;
import net.minecraft.AgeOfMinecraft.renders.RenderCow;
import net.minecraft.AgeOfMinecraft.renders.RenderCreeder;
import net.minecraft.AgeOfMinecraft.renders.RenderCreeper;
import net.minecraft.AgeOfMinecraft.renders.RenderEnderDragon;
import net.minecraft.AgeOfMinecraft.renders.RenderEnderman;
import net.minecraft.AgeOfMinecraft.renders.RenderEndermite;
import net.minecraft.AgeOfMinecraft.renders.RenderEversource;
import net.minecraft.AgeOfMinecraft.renders.RenderEvoker;
import net.minecraft.AgeOfMinecraft.renders.RenderGasterBlaster;
import net.minecraft.AgeOfMinecraft.renders.RenderGhast;
import net.minecraft.AgeOfMinecraft.renders.RenderGhasther;
import net.minecraft.AgeOfMinecraft.renders.RenderGiant;
import net.minecraft.AgeOfMinecraft.renders.RenderGuardian;
import net.minecraft.AgeOfMinecraft.renders.RenderIceGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderIceSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderIcyEnderCreeper;
import net.minecraft.AgeOfMinecraft.renders.RenderIllusioner;
import net.minecraft.AgeOfMinecraft.renders.RenderIronGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderLlama;
import net.minecraft.AgeOfMinecraft.renders.RenderMagicMissile;
import net.minecraft.AgeOfMinecraft.renders.RenderMagmaCube;
import net.minecraft.AgeOfMinecraft.renders.RenderMagmaGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderManaOrb;
import net.minecraft.AgeOfMinecraft.renders.RenderMooshroom;
import net.minecraft.AgeOfMinecraft.renders.RenderNullEntity;
import net.minecraft.AgeOfMinecraft.renders.RenderOcelot;
import net.minecraft.AgeOfMinecraft.renders.RenderParrot;
import net.minecraft.AgeOfMinecraft.renders.RenderPig;
import net.minecraft.AgeOfMinecraft.renders.RenderPigZombie;
import net.minecraft.AgeOfMinecraft.renders.RenderPolarBear;
import net.minecraft.AgeOfMinecraft.renders.RenderPortal;
import net.minecraft.AgeOfMinecraft.renders.RenderPrisonGolem;
import net.minecraft.AgeOfMinecraft.renders.RenderPrisonSlime;
import net.minecraft.AgeOfMinecraft.renders.RenderPrisonSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderRabbit;
import net.minecraft.AgeOfMinecraft.renders.RenderSans;
import net.minecraft.AgeOfMinecraft.renders.RenderSheep;
import net.minecraft.AgeOfMinecraft.renders.RenderShulker;
import net.minecraft.AgeOfMinecraft.renders.RenderSilverfish;
import net.minecraft.AgeOfMinecraft.renders.RenderSkeleton;
import net.minecraft.AgeOfMinecraft.renders.RenderSlime;
import net.minecraft.AgeOfMinecraft.renders.RenderSnowMan;
import net.minecraft.AgeOfMinecraft.renders.RenderSpider;
import net.minecraft.AgeOfMinecraft.renders.RenderSquid;
import net.minecraft.AgeOfMinecraft.renders.RenderStormSkull;
import net.minecraft.AgeOfMinecraft.renders.RenderVex;
import net.minecraft.AgeOfMinecraft.renders.RenderVillager;
import net.minecraft.AgeOfMinecraft.renders.RenderVindicator;
import net.minecraft.AgeOfMinecraft.renders.RenderWitch;
import net.minecraft.AgeOfMinecraft.renders.RenderWither;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStorm;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStormHead;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStormTentacle;
import net.minecraft.AgeOfMinecraft.renders.RenderWitherStormTentacleDevourer;
import net.minecraft.AgeOfMinecraft.renders.RenderWolf;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.RenderSnowball;
import net.minecraft.client.renderer.entity.RenderTippedArrow;
import net.minecraft.init.Items;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class ClientProxy extends CommonProxy {

  public void preInit(FMLPreInitializationEvent e) {
    renderEntities();
    EngenderGeneralEvent.musicTicker = new EngenderMusicEvent(Minecraft.getMinecraft());
    super.preInit(e);
  }
  
  public void init(FMLInitializationEvent e) {
    super.init(e);
  }
  
  public void postInit(FMLPostInitializationEvent e) {
    super.postInit(e);
    EItem.registerRenders();
    if (Loader.isModLoaded("abyssalcraft"))
      EItem.registerAbyRenders(); 
    if (Loader.isModLoaded("draconicevolution"))
      EItem.registerDracRenders(); 
    if (Loader.isModLoaded("mutantbeasts"))
      EItem.registerMutantRenders(); 
  }
  
  public void renderEntities() {
    RenderingRegistry.registerEntityRenderingHandler(EntityManaOrb.class, RenderManaOrb::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityAreaEffectCloudOther.class, RenderNullEntity::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityEversource.class, RenderEversource::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityIceSpider.class, RenderIceSpider::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityCreeder.class, RenderCreeder::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityIcyEnderCreeper.class, RenderIcyEnderCreeper::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityIceGolem.class, RenderIceGolem::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityMagmaGolem.class, RenderMagmaGolem::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPrisonSlime.class, RenderPrisonSlime::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPrisonSpider.class, RenderPrisonSpider::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPrisonGolem.class, RenderPrisonGolem::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityGhasther.class, RenderGhasther::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityAbomniableSnowman.class, RenderAbomniableSnowman::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityMagicMissile.class, RenderMagicMissile::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityEvoker.class, RenderEvoker::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityLlama.class, RenderLlama::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityIllusioner.class, RenderIllusioner::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityVindicator.class, RenderVindicator::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityVex.class, RenderVex::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPolarBear.class, RenderPolarBear::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityCaveSpider.class, RenderCaveSpider::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySpider.class, RenderSpider::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPig.class, RenderPig::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySheep.class, RenderSheep::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityCow.class, RenderCow::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityMooshroom.class, RenderMooshroom::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWolf.class, RenderWolf::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityChicken.class, RenderChicken::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityParrot.class, RenderParrot::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityOcelot.class, RenderOcelot::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityRabbit.class, RenderRabbit::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySilverfish.class, RenderSilverfish::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityEndermite.class, RenderEndermite::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityCreeper.class, RenderCreeper::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityEnderman.class, RenderEnderman::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySnowman.class, RenderSnowMan::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySkeleton.class, RenderSkeleton::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWitch.class, RenderWitch::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityBlaze.class, RenderBlaze::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPigZombie.class, RenderPigZombie::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySlime.class, RenderSlime::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityMagmaCube.class, RenderMagmaCube::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityGiant.class, RenderGiant::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityGhast.class, RenderGhast::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySquid.class, RenderSquid::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityVillager.class, RenderVillager::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityIronGolem.class, RenderIronGolem::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityBat.class, RenderBat::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityGuardian.class, RenderGuardian::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityElderGuardian.class, RenderGuardian::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityShulker.class, RenderShulker::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityEnderDragon.class, RenderEnderDragon::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWither.class, RenderWither::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityCommandBlockWither.class, RenderCommandBlockWither::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormSkull.class, RenderStormSkull::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStorm.class, RenderWitherStorm::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormHead.class, RenderWitherStormHead::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormTentacle.class, RenderWitherStormTentacle::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityWitherStormTentacleDevourer.class, RenderWitherStormTentacleDevourer::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPortal.class, RenderPortal::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityPortalLightning.class, RenderNullEntity::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityDisintigrationRay.class, RenderNullEntity::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityInvisibleFangsProjectile.class, RenderNullEntity::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityFrostRay.class, RenderNullEntity::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySnowballHarmful.class, manager -> new RenderSnowball<>(manager, Items.SNOWBALL, Minecraft.getMinecraft().getRenderItem()));
    RenderingRegistry.registerEntityRenderingHandler(EntityTippedArrowOther.class, RenderTippedArrow::new);
    RenderingRegistry.registerEntityRenderingHandler(EntitySans.class, RenderSans::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityBoneAttack.class, RenderBoneAttack::new);
    RenderingRegistry.registerEntityRenderingHandler(EntityGasterBlaster.class, RenderGasterBlaster::new);
  }
}
